version: "3.4"

# Production environment override
services:
  php:
    environment:
      APP_ENV: dev
      APP_SECRET: ${APP_SECRET}

  caddy:
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY}
