version: "3.4"

# Production environment override
services:
  pwa:
    image: ${API_PWA_IMAGE}

  php:
    image: ${API_PHP_IMAGE}
    environment:
      APP_ENV: prod
      SERVER_NAME: ${SERVER_NAME:-!CHANGEME!}
      TRUSTED_HOSTS: ${TRUSTED_HOSTS-!CHANGEME!}
    volumes:
      - ./../config/jwt:/srv/api/config/jwt
      - ./../config/secrets:/srv/api/config/secrets

  caddy:
    image: ${API_CADDY_IMAGE}
    environment:
      PWA_UPSTREAM: pwa:80