framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            email_priority_low:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    # Messenger will create then send to this exchange
                    exchange:
                        name: email
                        type: direct
                        default_publish_routing_key: low
                    # Messenger will create this queue & add binding keys
                    # The worker will know to consume from this queue
                    queues:
                        emails_low:
                            binding_keys: [low]
            email_priority_normal:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    # Messenger will create then send to this exchange
                    exchange:
                        name: email
                        type: direct
                        default_publish_routing_key: normal
                    # Messenger will create this queue & add binding keys
                    # The worker will know to consume from this queue
                    queues:
                        emails_normal:
                            binding_keys: [normal]
            email_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: email
                        type: direct
                        default_publish_routing_key: high
                    queues:
                        emails_high:
                            binding_keys: [high]

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            App\Message\EmailPasswordResetLink: email_priority_high
