monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: warning
            handler: rollbar
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        rollbar:
            type: service
            id: Rollbar\Monolog\Handler\RollbarHandler
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
