name: Clean Up

on:
  workflow_dispatch:
  delete:

jobs:
  docker-cleanup:
    name: Docker Clean Up
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get tag version
        id: get_tag
        run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF/refs\/tags\//} | sed 's/refs\/heads\///g')
      - name: Get Access Token
        run: |
          sudo apt install jq
          echo ::set-output name=HUB_TOKEN::$(echo $(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'${{ secrets.DH_USERNAME}}'", "password": "'${{ secrets.DH_TOKEN}}'"}' https://hub.docker.com/v2/users/login/ | jq -r .token))
      - name: Delete images
        run: echo $HUB_TOKEN
        env:
         ADMIN_IMAGE: ${{ secrets.DH_USERNAME }}/api-admin:${{ steps.get_tag.outputs.VERSION }}
         CLIENT_IMAGE: ${{ secrets.DH_USERNAME }}/api-client:${{ steps.get_tag.outputs.VERSION }}
         NGINX_IMAGE: ${{ secrets.DH_USERNAME }}/api-nginx:${{ steps.get_tag.outputs.VERSION }}
         PHP_IMAGE: ${{ secrets.DH_USERNAME }}/api-php:${{ steps.get_tag.outputs.VERSION }}
         VARNISH_IMAGE: ${{ secrets.DH_USERNAME }}/api-varnish:${{ steps.get_tag.outputs.VERSION }}
